use_frameworks!

platform :ios, '8.0'

target 'YCThreadSafeMutableCollection_Example' do
  pod 'YCThreadSafeMutableCollection', :path => '../'

  target 'YCThreadSafeMutableCollection_Tests' do
    inherit! :search_paths

    
  end
end
